/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_arielperez;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ariel
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        area3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Administracion de archivo de Texto");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButton1.setText("Salir del programa");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Contar palabras");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Añadir un archivo para administrarlo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
        });

        area2.setColumns(20);
        area2.setRows(5);
        jScrollPane2.setViewportView(area2);

        jButton4.setText("Top de las palabras");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        area3.setColumns(20);
        area3.setRows(5);
        jScrollPane3.setViewportView(area3);

        jButton5.setText("Combinaciones");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(143, 143, 143)
                                .addComponent(jButton5)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(aceptar)
                                        .addGap(35, 35, 35))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(55, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(aceptar)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Gracias por administrar sus archivos con nosotros");
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        area.append("\n");
        area.append("Cuenta de todas las palabras en su documento.");
        area.append("\n");
        area.append("\n");
        for (int i = 0; i < acumuladas.size(); i++) {
            area.append(acumuladas.get(i) + "    " + Cont.get(i) + "\n");
        }
        for (int i = 0; i < imp.size(); i++) {
            area.append(imp.get(i) + "   " + imp2.get(i) + "\n");
        }
        for (int i = 0; i < imp3.size(); i++) {
            area.append(imp3.get(i) + "   " + imp4.get(i) + "\n");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        JOptionPane.showMessageDialog(this, "Es hora de agregar un archivo que desees modificar con nosotros");
        acumuladas.clear();
        Cont.clear();
        lineas.clear();
        al.clear();
        ac.clear();
        al2.clear();
        ac2.clear();
        area.setText("");
        JFileChooser FC = new JFileChooser();
        FileNameExtensionFilter TEXTFILTER = new FileNameExtensionFilter("Archivos de Texto", "txt");
        FC.setFileFilter(TEXTFILTER);
        int action = FC.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            File Archivo = null;
            FileReader fr = null;
            BufferedReader br = null;
            String linea = "";
            String parsedLine = "";
            try {
                Archivo = FC.getSelectedFile();
                fr = new FileReader(Archivo);
                br = new BufferedReader(fr);
                while ((linea = br.readLine()) != null) {
                    parsedLine = "";
                    for (int i = 0; i < linea.length(); i++) {
                        String tempo = Character.toString(linea.charAt(i));
                        if (tempo.equals(",|.|?|!|¡|¿|'|;|:|#|$|")) {

                        } else {
                            parsedLine += tempo;
                        }
                    }
                    lineas.clear();
                    String[] cambiar = parsedLine.split(" ");
                    for (int i = 0; i < cambiar.length; i++) {
                        if (cambiar[i].matches("for|if|it|the|else|what|was|from|to|in|as|and|but|or|at|why|this|on|to|a|is|with")) {

                        } else {
                            lineas.add(cambiar[i]);
                        }
                    }
                    for (int i = 0; i < lineas.size(); i++) {
                        if (acumuladas.contains(lineas.get(i))) {
                            for (int j = 0; j < acumuladas.size(); j++) {
                                if (acumuladas.get(j).equals(lineas.get(i))) {
                                    int palabra = Cont.get(j);
                                    palabra++;
                                    Cont.set(j, palabra);
                                }
                            }
                        } else {
                            acumuladas.add(lineas.get(i));
                            Cont.add(1);
                        }
                    }
                    if (lineas.size() >= 4) {
                        String d = "";
                        d = "";
                        d = lineas.get(0) + " " + lineas.get(1);
                        al.add(d);
                        ac.add(1);
                        d = "";
                        d = lineas.get(0) + " " + lineas.get(2);
                        al.add(d);
                        ac.add(1);
                        d = "";
                        d = lineas.get(0) + " " + lineas.get(3);
                        al.add(d);
                        ac.add(1);
                        d = "";
                        d = lineas.get(1) + " " + lineas.get(2);
                        al.add(d);
                        ac.add(1);
                        d = "";
                        d = lineas.get(1) + " " + lineas.get(3);
                        al.add(d);
                        ac.add(1);
                        d = "";
                        d = lineas.get(3) + " " + lineas.get(2);
                        al.add(d);
                        d = "";
                        d = lineas.get(0) + " " + lineas.get(1) + " " + lineas.get(2);
                        al2.add(d);
                        ac2.add(1);
                        d = "";
                        d = lineas.get(0) + " " + lineas.get(1) + " " + lineas.get(3);
                        al2.add(d);
                        ac2.add(1);
                        d = "";
                        d = lineas.get(3) + " " + lineas.get(2) + " " + lineas.get(1);
                        al2.add(d);
                        ac2.add(1);
                        d = "";
                        d = lineas.get(1) + " " + lineas.get(3) + " " + lineas.get(2);
                        al2.add(d);
                        ac2.add(1);
                    }
                }
                JOptionPane.showMessageDialog(this, "Aprete ahora el siguiente boton para modificarlo");
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jButton3MouseClicked

    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked
        // TODO add your handling code here:
        String vacio = "";
        if (area.getText().equals(vacio)) {
            JOptionPane.showMessageDialog(this, "No ha terminado de administrarse el archivo");
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_aceptarMouseClicked

    public ArrayList<Integer> Top() {
        ArrayList<Integer> a = new ArrayList();
        for (int i = 0; i < Cont.size(); i++) {
            a.add(Cont.get(i));
        }
        Collections.sort(a, Collections.reverseOrder());
        ArrayList<Integer> arreglo = new ArrayList();
        for (int i = 0; i < a.size(); i++) {
            if (arreglo.contains(a.get(i))) {
            } else {
                arreglo.add(a.get(i));
            }
        }
        return arreglo;
    }


    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        ArrayList<Integer> topten = Top();
        int t = 1;
        area2.append("Palabras mas utilizadas en este documento que nos brindo \n");
        for (int i = 0; i < topten.size(); i++) {
            for (int j = 0; j < Cont.size(); j++) {
                if (Cont.get(j).equals(topten.get(i)) && t <= 10) {
                    area2.append(t + "." + "  " + acumuladas.get(j) + "   " + Cont.get(j) + "\n");
                }
            }
            t++;
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {
            area3.append("\n");
            area3.append("Todas las combinaciones del documento son:. \n");
            area3.append("\n");
            Collections.sort(al);
            for (int i = 0; i < al.size(); i++) {
                area3.append(al.get(i) + "   " + ac.get(i) + "\n");
            }
            Collections.sort(al2);
            for (int i = 0; i < al2.size(); i++) {
                area3.append(al2.get(i) + "   " + ac2.get(i) + "\n");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    ArrayList<String> imp = new ArrayList();
    ArrayList<Integer> imp2 = new ArrayList();
    ArrayList<String> imp3 = new ArrayList();
    ArrayList<Integer> imp4 = new ArrayList();
    ArrayList<String> lineas = new ArrayList();
    ArrayList<String> acumuladas = new ArrayList();
    ArrayList<Integer> Cont = new ArrayList();
    ArrayList<String> al = new ArrayList();
    ArrayList<Integer> ac = new ArrayList();
    ArrayList<String> al2 = new ArrayList();
    ArrayList<Integer> ac2 = new ArrayList();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextArea area;
    private javax.swing.JTextArea area2;
    private javax.swing.JTextArea area3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
